version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  recaptcha:
    lang: node10-express-service
    handler: ./recaptcha
    image: recaptcha:latest
    secrets:
      - secrets

